// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzpoxyvfvqygjstinewn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6cG94eXZmdnF5Z2pzdGluZXduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMDQ2ODAsImV4cCI6MjA2NzY4MDY4MH0.P6bcN8y-ojpVmr2W7p1FcgZlNh3lxYuOtqLBakeyQdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});